# Generated by Django 5.2 on 2025-04-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('applicant', 'Applicant'), ('leader', 'Team Leader'), ('company', 'Company')], default='applicant', max_length=20, null=True),
        ),
    ]
